
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

WPM_ENABLE = yes

MOUSEKEY_ENABLE = yes # Mouse keys
RGBLIGHT_ENABLE = yes
CAPS_WORD_ENABLE = yes

MAGIC_ENABLE = no
LTO_ENABLE = yes
MUSIC_ENABLE = no
